all: producent konsument producent2 konsument2

producent: producent.c
	gcc producent.c -o producent

konsument: konsument.c
	gcc konsument.c -o konsument

producent2: producent2.c
	gcc producent2.c -o producent2

konsument2: konsument2.c
	gcc konsument2.c -o konsument2